# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Soundboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Soundboard
pod 'JGProgressHUD'
#pod 'Firebase/Core'
#pod 'Firebase/Messaging'
#pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'FirebaseAuth', '~> 8.9'

  target 'SoundboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoundboardUITests' do
    # Pods for testing
  end

#  target 'OneSignalNotificationServiceExtension' do
#    # Comment the next line if you don't want to use dynamic frameworks
#    use_frameworks!
#    pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
#  end
  
end


